---
- name: Install requirement packages
  become: true
  apt:
    name:
      - sshpass
      - asciinema
      - python3-pip
      - python3-psycopg2
      - acl                           # https://github.com/georchestra/ansible/issues/55#issuecomment-651043423
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure a locale exists
  community.general.locale_gen:
    name: ru_RU.UTF-8
    state: present

- name: Disable MOTD display when opening SSH session
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pam.d/sshd
    state: absent
    regexp: '^session    optional     pam_motd.so'
    backup: true

- name: Set ip forwarding
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Set route to localnet
  become: true
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.route_localnet
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Configure SSHD - KexAlgorithms 
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    backup: true
    regexp: '^KexAlgorithms '
    line: "KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1"
    insertafter: "^# Ciphers and keying"
  notify: Restart ssh.service

- name: Disable sFTP over SSH
  become: true
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '^(Subsystem sftp.*)$'
    replace: '# \1'
  notify: Restart ssh.service

- name: Flush handlers
  meta: flush_handlers
