---
- name: Install requirement packages
  become: true
  apt:
    name:
      - python3-pip
      - python3-psycopg2
      - acl                           # https://github.com/georchestra/ansible/issues/55#issuecomment-651043423
    update_cache: yes
    cache_valid_time: 3600
