---
- name: Start pyRMA Web Interface
  become: true
  ansible.builtin.systemd:
    name: pyrma-web.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: Start pyRMA Firewall
  become: true
  ansible.builtin.systemd:
    name: pyrma-firewall.service
    state: started
    enabled: yes
    daemon_reload: yes
